export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const GET_ALL_SELECTED_PRODUCTS = 'GET_ALL_SELECTED_PRODUCTS';
export const UPDATE_AMOUNT_OF_SELECTED_PRODUCT = 'UPDATE_AMOUNT_OF_SELECTED_PRODUCT';
export const SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD';
export const DELETE_SELECTED_PRODUCT = 'DELETE_SELECTED_PRODUCT';
